sina:
  api_key: 3855039984
  api_key_secret: fc3f8f430692a5b8bcd01b35a83d07fe
  site: http://api.t.sina.com.cn
  request_token_path: /oauth/request_token
  access_token_path: /oauth/access_token
  authorize_path: /oauth/authorize
  signature_method: HMAC-SHA1
  scheme: header
  realm: http//localhost:3000